// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tools/:toolId": {
    params: {
      "toolId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tools/:toolId";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/tool.tsx": {
    id: "routes/tool";
    page: "/tools/:toolId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/tool": typeof import("./app/routes/tool.tsx");
};